version: '3.8'

services:
  web:
    build: .
    # This command applies any pending migrations, compiles translations, and starts the development server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py compilemessages &&
             uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      # Mounts the current directory to /app in the container for live-reloading during development
      # This also persists your local db.sqlite3 file
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=core.settings