# Generated by Django 5.2.8 on 2026-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_academiccouncilfile_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('news_title', models.CharField(default='Новости', max_length=200, verbose_name='Заголовок новостей')),
                ('news_title_ru', models.CharField(default='Новости', max_length=200, null=True, verbose_name='Заголовок новостей')),
                ('news_title_ky', models.CharField(default='Новости', max_length=200, null=True, verbose_name='Заголовок новостей')),
                ('news_title_en', models.CharField(default='Новости', max_length=200, null=True, verbose_name='Заголовок новостей')),
                ('announcements_title', models.CharField(default='Объявления', max_length=200, verbose_name='Заголовок объявлений')),
                ('announcements_title_ru', models.CharField(default='Объявления', max_length=200, null=True, verbose_name='Заголовок объявлений')),
                ('announcements_title_ky', models.CharField(default='Объявления', max_length=200, null=True, verbose_name='Заголовок объявлений')),
                ('announcements_title_en', models.CharField(default='Объявления', max_length=200, null=True, verbose_name='Заголовок объявлений')),
                ('library_title', models.CharField(default='Электронная библиотека', max_length=200, verbose_name='Заголовок библиотеки')),
                ('library_title_ru', models.CharField(default='Электронная библиотека', max_length=200, null=True, verbose_name='Заголовок библиотеки')),
                ('library_title_ky', models.CharField(default='Электронная библиотека', max_length=200, null=True, verbose_name='Заголовок библиотеки')),
                ('library_title_en', models.CharField(default='Электронная библиотека', max_length=200, null=True, verbose_name='Заголовок библиотеки')),
                ('library_link', models.URLField(blank=True, verbose_name='Ссылка на библиотеку (внешняя)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_in_footer',
            field=models.BooleanField(default=True, verbose_name='Показывать в подвале'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_in_header',
            field=models.BooleanField(default=True, verbose_name='Показывать в шапке'),
        ),
    ]
