# Generated by Django 5.2.8 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sitesettings_sociallink_show_in_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='Иконка'),
        ),
    ]
