# Generated by Django 5.2.8 on 2026-05-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='main_page_slider/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд главной страницы',
                'verbose_name_plural': 'Слайдер главной страницы',
                'ordering': ['-date'],
            },
        ),
    ]
