# Generated by Django 5.2.8 on 2026-05-25 04:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mainpageslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='map_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='educationdirection',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='internationalcooperationlink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_link_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_link_ky',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_link_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка об академии'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='library_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на библиотеку (внешняя)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Ссылка'),
        ),
        migrations.CreateModel(
            name='AcademyCharterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.academycharter', verbose_name='Устав академии')),
            ],
            options={
                'verbose_name': 'Ссылка устава академии',
                'verbose_name_plural': 'Ссылки устава академии',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetProgramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('budget_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.budgetprogram', verbose_name='Проект бюджетных программ')),
            ],
            options={
                'verbose_name': 'Ссылка проекта бюджетных программ',
                'verbose_name_plural': 'Ссылки проекта бюджетных программ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BulletinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.bulletin', verbose_name='Вестник')),
            ],
            options={
                'verbose_name': 'Ссылка вестника',
                'verbose_name_plural': 'Ссылки вестника',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TradeUnionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('trade_union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.tradeunion', verbose_name='Профсоюзный комитет')),
            ],
            options={
                'verbose_name': 'Ссылка профсоюзного комитета',
                'verbose_name_plural': 'Ссылки профсоюзного комитета',
                'ordering': ['order', 'id'],
            },
        ),
    ]
