# Placeholder merge-compatible migration.
# The production/main branch already contains a migration with this name.
# Keeping this no-op locally lets the CMS cleanup migration depend on that leaf
# and removes the multiple-0008 leaf conflict when the branches are combined.

# Generated by Django 5.2.8 on 2026-07-11 18:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_announcement_date_alter_contact_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutacademy',
            name='additional_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='additional_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='additional_description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='additional_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block1_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание блока 1'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block1_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 1'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block1_description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 1'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block1_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 1'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block2_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание блока 2'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block2_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 2'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block2_description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 2'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='block2_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание блока 2'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='mission_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='mission_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='mission_description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='mission_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание миссии'),
        ),
        migrations.AlterField(
            model_name='academichonesty',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academichonesty',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academichonesty',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academichonesty',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academycharter',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academycharter',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academycharter',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academycharter',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academyhistory',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academyhistory',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academyhistory',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academyhistory',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academylogo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academylogo',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academylogo',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='academylogo',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='budgetprogram',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactdepartment',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactdepartment',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactdepartment',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactdepartment',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationdirection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationdirection',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationdirection',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationdirection',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='honoraryprofessor',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='honoraryprofessor',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='honoraryprofessor',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='honoraryprofessor',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='internationalcooperation',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='libraryresource',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание об академии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание об академии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organizationalstructure',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradeunion',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradeunion',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradeunion',
            name='description_ky',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradeunion',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
    ]
