# Generated by Django 5.2.8 on 2026-07-18 14:44

import django.db.models.deletion
from django.db import migrations, models



def seed_admin_structure(apps, schema_editor):
    AdminPage = apps.get_model("app", "AdminPage")
    PageBlock = apps.get_model("app", "PageBlock")

    def page(title, slug, group, order, parent=None, description='', redirect_url='', is_development=False):
        return AdminPage.objects.create(
            title=title, title_ru=title, slug=slug, group=group, parent=parent,
            order=order, description=description, description_ru=description,
            redirect_url=redirect_url, is_development=is_development,
        )

    def block(page_obj, title, order, block_type='text', description=''):
        return PageBlock.objects.create(
            page=page_obj, title=title, title_ru=title, order=order,
            block_type=block_type, description=description, description_ru=description,
        )

    home = page('Главная страница', 'home', 'home', 10)
    for i, item in enumerate([
        ('Лого', 'photo_text'), ('Карусель фотографий', 'slider'), ('Дата и текст поверх фотографий', 'slider'),
        ('Абитуриент 2026', 'photo_text'), ('Вход в AVN', 'link'), ('ЭОП', 'link'), ('Новости', 'text'),
        ('Образование в академии — блок 1', 'text'), ('Образование в академии — блок 2', 'text'),
        ('Образование в академии — блок 3', 'text'), ('Образование в академии — блок 4', 'text'),
        ('Об академии', 'text'), ('Количество преподавателей', 'number'), ('Количество докторов наук и профессионалов', 'number'),
        ('Количество окончивших студентов', 'number'), ('Процент успеха в своей сфере', 'number'),
        ('Ценность Академии 1', 'text'), ('Ценность Академии 2', 'text'), ('Ценность Академии 3', 'text'), ('Ценность Академии 4', 'text'),
        ('Ценность Академии 5', 'text'), ('Ценность Академии 6', 'text'), ('Ценность Академии 7', 'text'), ('Ценность Академии 8', 'text'),
        ('Ссылка 1', 'link'), ('Ссылка 2', 'link'), ('Ссылка 3', 'link'), ('Ссылка 4', 'link'),
        ('Facebook', 'social'), ('Instagram', 'social'), ('YouTube', 'social'),
    ], 1):
        block(home, item[0], i, item[1])

    about = page('О нас', 'about', 'about', 20)
    for i, item in enumerate(['Главная фотография и описание всего блока', 'АГУПКР - это: блок 1', 'АГУПКР - это: блок 2', 'Миссия Академии'], 1):
        block(about, item, i, 'photo_text' if i == 1 else 'text')
    for j, title in enumerate(['Приветствие ректора', 'Устав', 'Стратегия развития', 'Антикоррупционная политика', 'Руководство', 'Ученый совет', 'Структура академии', 'Визуальный стиль', 'Сми о нас'], 1):
        p = page(title, f'about-{j}', 'about', 20 + j, about, is_development=(title == 'Структура академии'))
        if title in {'Руководство'}:
            block(p, 'Блок члена руководства', 1, 'photo_text')
        elif title == 'Ученый совет':
            block(p, 'PDF файл ученого совета', 1, 'pdf')
        elif title == 'Устав':
            block(p, 'PDF файл устава', 1, 'pdf')

    for group, root_title, subs, base in [
        ('abdrakhmanov', 'Жусуп Абдрахманов', ['Биография', 'Дневники Жусупа Абдрахманова', 'Курс', 'Значок'], 40),
        ('ideology', 'Национальная Идеология', ['Докторина', 'Курс'], 50),
        ('professional_development', 'Профессиональное развитие', ['Переподготовка и пов-е квалификации', 'Каталог курсов', 'Форма регистрации на курсы', 'НПА и локальные акты'], 60),
        ('education', 'Образование', ['Лицензии и сертификаты', 'Программы ВПО', 'Докторантура', 'Академическая политика', 'Почетные профессора', 'ППС', 'НПА и локальные акты'], 70),
        ('science', 'Наука и инновации', ['Реализация госзаказа на проведение НИР', 'Вестник АГУПКР', 'Библиотека', 'Библиотека', 'НПА и локальные акты'], 80),
        ('international', 'Международное сотрудничество', ['Попечительский совет', 'Распоряжение РАПКР о ПС', 'Положение о ПС', 'Члены ПС'], 90),
    ]:
        root = page(root_title, group, group, base)
        for j, title in enumerate(subs, 1):
            p = page(title, f'{group}-{j}', group, base + j, root)
            if 'Каталог' in title or 'Форма' in title:
                block(p, 'Ссылка', 1, 'link')
            if 'НПА' in title or 'Вестник' in title:
                block(p, 'PDF файл', 1, 'pdf')
            if title in {'Почетные профессора', 'ППС', 'Члены ПС'}:
                block(p, 'Добавляемый блок: фото + описание', 1, 'photo_text')

    page('Контакты', 'contacts', 'contacts', 100)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_announcement_date_alter_contact_map_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название блока"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название блока"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название блока"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название блока"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Системный URL"
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("home", "Главная страница"),
                            ("about", "О нас"),
                            ("abdrakhmanov", "Жусуп Абдрахманов"),
                            ("ideology", "Национальная Идеология"),
                            ("professional_development", "Профессиональное развитие"),
                            ("education", "Образование"),
                            ("science", "Наука и инновации"),
                            ("international", "Международное сотрудничество"),
                            ("contacts", "Контакты"),
                        ],
                        max_length=40,
                        verbose_name="Главная страница раздела",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "main_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/main/",
                        verbose_name="Главная фотография",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_ky",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "redirect_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ссылка на редирект"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pages/pdfs/",
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "is_development",
                    models.BooleanField(default=False, verbose_name="В разработке"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subpages",
                        to="app.adminpage",
                        verbose_name="Родительская страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "01. Страницы сайта",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст / description"),
                            ("photo_text", "Фото + description"),
                            ("link", "Ссылка под текстом"),
                            ("pdf", "PDF файл скрытый под текстом"),
                            ("number", "Текстовое поле с цифрой"),
                            ("social", "Ссылка на социальную сеть"),
                            ("slider", "Слайд карусели"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип блока",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название / текст ссылки",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название / текст ссылки",
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название / текст ссылки",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название / текст ссылки",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_ky",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/blocks/photos/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pages/blocks/files/",
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Значение / цифра"
                    ),
                ),
                (
                    "value_ru",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Значение / цифра",
                    ),
                ),
                (
                    "value_ky",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Значение / цифра",
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Значение / цифра",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="app.adminpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок страницы",
                "verbose_name_plural": "02. Блоки страниц",
                "ordering": ["page__order", "order", "id"],
            },
        ),
        migrations.RunPython(seed_admin_structure, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="AboutAcademy",
        ),
        migrations.RemoveField(
            model_name="academiccouncilfile",
            name="council",
        ),
        migrations.DeleteModel(
            name="AcademicHonesty",
        ),
        migrations.RemoveField(
            model_name="academycharterlink",
            name="charter",
        ),
        migrations.DeleteModel(
            name="AcademyHistory",
        ),
        migrations.DeleteModel(
            name="AcademyLogo",
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
        migrations.RemoveField(
            model_name="budgetprogramlink",
            name="budget_program",
        ),
        migrations.RemoveField(
            model_name="bulletinlink",
            name="bulletin",
        ),
        migrations.RemoveField(
            model_name="bulletinfile",
            name="bulletin",
        ),
        migrations.RemoveField(
            model_name="contactdepartment",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="department",
            name="structure",
        ),
        migrations.DeleteModel(
            name="EducationDirection",
        ),
        migrations.DeleteModel(
            name="EducationProgram",
        ),
        migrations.DeleteModel(
            name="HonoraryProfessor",
        ),
        migrations.RemoveField(
            model_name="internationalcooperationlink",
            name="cooperation",
        ),
        migrations.DeleteModel(
            name="LegalDocument",
        ),
        migrations.RemoveField(
            model_name="libraryresource",
            name="category",
        ),
        migrations.DeleteModel(
            name="MainPage",
        ),
        migrations.DeleteModel(
            name="MainPageSlider",
        ),
        migrations.RemoveField(
            model_name="newsphoto",
            name="news",
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.RemoveField(
            model_name="qualitymanagementfile",
            name="quality",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.RemoveField(
            model_name="tradeunionlink",
            name="trade_union",
        ),
        migrations.DeleteModel(
            name="AcademicCouncil",
        ),
        migrations.DeleteModel(
            name="AcademicCouncilFile",
        ),
        migrations.DeleteModel(
            name="AcademyCharter",
        ),
        migrations.DeleteModel(
            name="AcademyCharterLink",
        ),
        migrations.DeleteModel(
            name="BudgetProgram",
        ),
        migrations.DeleteModel(
            name="BudgetProgramLink",
        ),
        migrations.DeleteModel(
            name="BulletinLink",
        ),
        migrations.DeleteModel(
            name="Bulletin",
        ),
        migrations.DeleteModel(
            name="BulletinFile",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="ContactDepartment",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="OrganizationalStructure",
        ),
        migrations.DeleteModel(
            name="InternationalCooperation",
        ),
        migrations.DeleteModel(
            name="InternationalCooperationLink",
        ),
        migrations.DeleteModel(
            name="LibraryCategory",
        ),
        migrations.DeleteModel(
            name="LibraryResource",
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="NewsPhoto",
        ),
        migrations.DeleteModel(
            name="QualityManagement",
        ),
        migrations.DeleteModel(
            name="QualityManagementFile",
        ),
        migrations.DeleteModel(
            name="TradeUnion",
        ),
        migrations.DeleteModel(
            name="TradeUnionLink",
        ),
    ]
