# Generated by Django 5.2.8 on 2026-07-19 16:49

from django.db import migrations, models


def update_home_page_blocks(apps, schema_editor):
    AdminPage = apps.get_model("app", "AdminPage")
    PageBlock = apps.get_model("app", "PageBlock")

    try:
        home = AdminPage.objects.get(slug="home")
    except AdminPage.DoesNotExist:
        return

    photo_titles = [
        "Фото главной страницы 1",
        "Фото главной страницы 2",
        "Фото главной страницы 3",
    ]

    missing_titles = [
        title for title in photo_titles
        if not PageBlock.objects.filter(page=home, title=title).exists()
    ]
    if missing_titles:
        PageBlock.objects.filter(page=home, order__gte=4).update(order=models.F("order") + len(missing_titles))
        for index, title in enumerate(missing_titles, start=4):
            PageBlock.objects.create(
                page=home,
                block_type="slider",
                title=title,
                title_ru=title,
                order=index,
            )

    about_blocks = list(
        PageBlock.objects.filter(page=home, title="Об академии").order_by("order", "id")
    )
    for duplicate in about_blocks[1:]:
        duplicate.delete()



class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_adminpage_pageblock_delete_legacy_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для редиректа всей страницы используйте поле «Ссылка на редирект».",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="adminpage",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для редиректа всей страницы используйте поле «Ссылка на редирект».",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="adminpage",
            name="description_ky",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для редиректа всей страницы используйте поле «Ссылка на редирект».",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="adminpage",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для редиректа всей страницы используйте поле «Ссылка на редирект».",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для блоков AVN/ЭОП и других редиректов используйте отдельное поле «Ссылка» ниже.",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для блоков AVN/ЭОП и других редиректов используйте отдельное поле «Ссылка» ниже.",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="description_ky",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для блоков AVN/ЭОП и других редиректов используйте отдельное поле «Ссылка» ниже.",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Можно вставлять ссылки через CKEditor. Для блоков AVN/ЭОП и других редиректов используйте отдельное поле «Ссылка» ниже.",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Заполняйте для блоков типа «Ссылка», например AVN или ЭОП. Ссылка нормализуется автоматически.",
                max_length=500,
                verbose_name="Ссылка",
            ),
        ),
        migrations.RunPython(update_home_page_blocks, migrations.RunPython.noop),
    ]
