# Generated by Django 5.2.8 on 2026-07-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_adminpage_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=160, unique=True, verbose_name="Системный URL"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="news/cards/", verbose_name="Фото для списка новостей"
                    ),
                ),
                ("description", models.TextField(verbose_name="Краткое описание")),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Краткое описание"),
                ),
                (
                    "description_ky",
                    models.TextField(null=True, verbose_name="Краткое описание"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Краткое описание"),
                ),
                (
                    "detail_description",
                    models.TextField(verbose_name="Описание на странице новости"),
                ),
                (
                    "detail_description_ru",
                    models.TextField(
                        null=True, verbose_name="Описание на странице новости"
                    ),
                ),
                (
                    "detail_description_ky",
                    models.TextField(
                        null=True, verbose_name="Описание на странице новости"
                    ),
                ),
                (
                    "detail_description_en",
                    models.TextField(
                        null=True, verbose_name="Описание на странице новости"
                    ),
                ),
                (
                    "detail_photo_1",
                    models.ImageField(
                        upload_to="news/details/", verbose_name="Фото новости 1"
                    ),
                ),
                (
                    "detail_photo_2",
                    models.ImageField(
                        upload_to="news/details/", verbose_name="Фото новости 2"
                    ),
                ),
                (
                    "detail_photo_3",
                    models.ImageField(
                        upload_to="news/details/", verbose_name="Фото новости 3"
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "03. Новости",
                "ordering": ["order", "-published_at", "-id"],
            },
        ),
    ]
