# Generated by Django 5.2.8 on 2026-08-17 03:55

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_news_photos(apps, schema_editor):
    News = apps.get_model("app", "News")
    NewsPhoto = apps.get_model("app", "NewsPhoto")
    photos = []
    for news in News.objects.all().iterator():
        for order in range(1, 4):
            photo = getattr(news, f"detail_photo_{order}")
            if photo:
                photos.append(NewsPhoto(news_id=news.pk, photo=photo, order=order))
    NewsPhoto.objects.bulk_create(photos)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="home_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Используется только для трех новостей в подразделе 1.5.1.",
                verbose_name="Порядок на главной",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="show_on_home",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="detail_photo_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/details/",
                verbose_name="Фото новости 1",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="detail_photo_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/details/",
                verbose_name="Фото новости 2",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="detail_photo_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/details/",
                verbose_name="Фото новости 3",
            ),
        ),
        migrations.CreateModel(
            name="NewsPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="news/details/", verbose_name="Фотография"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_photos",
                        to="app.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография новости",
                "verbose_name_plural": "Фотографии страницы новости",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_legacy_news_photos, migrations.RunPython.noop),
    ]
