# Generated by Django 5.2.8 on 2026-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_news_home_order_news_show_on_home_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminpage",
            name="content_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название контента"
            ),
        ),
        migrations.AddField(
            model_name="adminpage",
            name="content_title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название контента"
            ),
        ),
        migrations.AddField(
            model_name="adminpage",
            name="content_title_ky",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название контента"
            ),
        ),
        migrations.AddField(
            model_name="adminpage",
            name="content_title_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название контента"
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Можно прикрепить файл к блоку любого типа.",
                null=True,
                upload_to="pages/blocks/files/",
                verbose_name="Прикрепленный файл",
            ),
        ),
    ]
