# Generated by Django 5.2.8 on 2026-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_adminpage_content_title_adminpage_content_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblock",
            name="contacts",
            field=models.CharField(blank=True, max_length=500, verbose_name="Контакты"),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="contacts_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Контакты"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="contacts_ky",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Контакты"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="contacts_ru",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Контакты"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="short_information",
            field=models.TextField(blank=True, verbose_name="Краткая информация"),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="short_information_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткая информация"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="short_information_ky",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткая информация"
            ),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="short_information_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткая информация"
            ),
        ),
        migrations.AlterField(
            model_name="pageblock",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Заполняйте для блоков типа «Ссылка», AVN/ЭОП и блоков партнеров. Ссылка нормализуется автоматически.",
                max_length=500,
                verbose_name="Ссылка / сайт партнера",
            ),
        ),
    ]
